{{- if .Values.global.rbacEnable }}
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1" }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- else if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1alpha1" }}
apiVersion: rbac.authorization.k8s.io/v1alpha1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
{{- end }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "alameda.fullname" . }}
  labels:
    app: alameda
    component: {{ .Values.global.component.operator.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "alameda.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "alameda.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
