apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alameda.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.operator.name }}
spec:
  replicas: {{ .Values.global.component.operator.replicaCount }}
  selector:
    matchLabels:
      app: alameda
      component: {{ .Values.global.component.operator.name }}
  template:
    metadata:
      labels:
        app: alameda
        component: {{ .Values.global.component.operator.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace   
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
            - name: ALAMEDA_OPERATOR_DATAHUB_ADDRESS
              value: "{{ .Values.global.component.datahub.name }}.{{ .Release.Namespace }}:{{ .Values.global.component.datahub.service.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: podinfo
            mountPath: /etc/podinfo
            readOnly: false
          readinessProbe:
            exec:
              command:
              - /usr/local/bin/manager
              - --readiness-probe
            initialDelaySeconds: 5
            failureThreshold: 20
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/manager
              - --liveness-probe
            initialDelaySeconds: 5
            failureThreshold: 20
            periodSeconds: 5
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
    {{- if .Values.image.accessToken }}
      imagePullSecrets:
        - name: {{ include "alameda.fullname" . }}-imagepull
    {{- end }}
    {{- if .Values.global.rbacEnable }}
      serviceAccountName: {{ include "alameda.fullname" . }}
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
