apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alameda.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.operator.name }}
    app.kubernetes.io/name: {{ include "alameda.name" . }}
    helm.sh/chart: {{ include "alameda.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.global.component.operator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "alameda.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "alameda.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ALAMEDA_OPERATOR_DATAHUB_ADDRESS
              value: "{{ .Values.global.component.datahub.name }}.{{ .Release.Namespace }}:{{ .Values.global.component.datahub.service.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: podinfo
            mountPath: /etc/podinfo
            readOnly: false
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
    {{- if .Values.image.accessToken }}
      imagePullSecrets:
        - name: {{ include "alameda.fullname" . }}-imagepull
    {{- end }}
    {{- if .Values.global.rbacEnable }}
      serviceAccountName: {{ include "alameda.fullname" . }}
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
