{{- if .Values.global.rbacEnable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alameda.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.operator.name }}
{{- end }}
