apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admission-controller.fullname" . }}
  labels:
    app: alameda
    component: {{ .Values.global.component.admission.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alameda
      component: {{ .Values.global.component.admission.name }}
  template:
    metadata:
      labels:
        app: alameda
        component: {{ .Values.global.component.admission.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace   
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
            - name: ALAMEDA_ADMCTL_CA_CERT_FILE
              value: "/etc/tls-certs/ca.crt"
            - name: ALAMEDA_ADMCTL_TLS_CERT_FILE
              value: "/etc/tls-certs/tls.crt"
            - name: ALAMEDA_ADMCTL_TLS_PRIVATE_KEY_FILE
              value: "/etc/tls-certs/tls.key"
            - name: ALAMEDA_ADMCTL_DEPLOYED_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: ALAMEDA_ADMCTL_ENABLE
              value: "{{ .Values.global.executionEnable }}"
            - name: ALAMEDA_ADMCTL_DATAHUB_ADDRESS
              value: "{{ .Values.global.component.datahub.name }}.{{ .Release.Namespace }}:{{ .Values.global.component.datahub.service.port }}"
#            - name: ALAMEDA_ADMCTL_LOG_OUTPUT_LEVEL
#              value: "debug"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            exec:
              command:
              - /usr/local/bin/admission-controller
              - probe
              - --type=readiness
            failureThreshold: 20
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/admission-controller
              - probe
              - --type=liveness
            failureThreshold: 20
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
          - mountPath: /etc/tls-certs
            name: tls-certs
            readOnly: true
    {{- if .Values.image.accessToken }}
      imagePullSecrets:
        - name: {{ include "admission-controller.fullname" . }}-imagepull
    {{- end }}
      volumes:
      - name: tls-certs
        secret:
          secretName: {{ include "admission-controller.fullname" . }}-tls
    {{- if .Values.global.rbacEnable }}
      serviceAccountName: {{ include "admission-controller.fullname" . }}
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
