apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "admission-controller.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.admission.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "admission-controller.gen-certs" . ) | indent 2 }}

{{- if .Values.image.accessToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admission-controller.fullname" . }}-imagepull
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.admission.name }}
data:
  .dockerconfigjson: {{ .Values.image.accessToken }}
type: kubernetes.io/dockerconfigjson
{{- end }}
