{{- if .Values.global.rbacEnable }}
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1" }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- else if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1alpha1" }}
apiVersion: rbac.authorization.k8s.io/v1alpha1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
{{- end }}
kind: ClusterRole
metadata:
  labels:
    app: alameda
    component: {{ .Values.global.component.evictioner.name }}
  name: {{ include "evictioner.fullname" . }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - delete
- apiGroups:
    - autoscaling.containers.ai
  resources:
    - alamedascalers
    - alamedarecommendations
  verbs:
    - get
{{- end }}

