apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evictioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.evictioner.name }}
spec:
  replicas: {{ .Values.global.component.evictioner.replicaCount }}
  selector:
    matchLabels:
      app: alameda
      component: {{ .Values.global.component.evictioner.name }}
  template:
    metadata:
      labels:
        app: alameda
        component: {{ .Values.global.component.evictioner.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ALAMEDA_EVICTIONER_DATAHUB_ADDRESS
              value: "{{ .Values.global.component.datahub.name }}.{{ .Release.Namespace }}:{{ .Values.global.component.datahub.service.port }}"
            - name: ALAMEDA_EVICTIONER_EVICTION_ENABLE
              value: "{{ .Values.global.executionEnable }}"
#            - name: ALAMEDA_EVICTIONER_LOG_OUTPUT_LEVEL
#              value: "debug"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            exec:
              command:
              - /usr/local/bin/evictioner
              - probe
              - --type=readiness
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/evictioner
              - probe
              - --type=liveness
            initialDelaySeconds: 5
            periodSeconds: 5
    {{- if .Values.image.accessToken }}
      imagePullSecrets:
        - name: {{ include "evictioner.fullname" . }}-imagepull
    {{- end }}
    {{- if .Values.global.rbacEnable }}
      serviceAccountName: {{ include "evictioner.fullname" . }}
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
