{{- if .Values.global.rbacEnable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "evictioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.evictioner.name }}
{{- end }}
