apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alameda-ai.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.alamedaai.name }}
spec:
  replicas: {{ .Values.global.component.alamedaai.replicaCount }}
  selector:
    matchLabels:
      app: alameda
      component: {{ .Values.global.component.alamedaai.name }}
  template:
    metadata:
      labels:
        app: alameda
        component: {{ .Values.global.component.alamedaai.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATAHUB_ADDRESS
              value: "{{ .Values.global.component.datahub.name }}.{{ .Release.Namespace }}:{{ .Values.global.component.datahub.service.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- if .Values.image.accessToken }}
      imagePullSecrets:
        - name: {{ include "alameda-ai.fullname" . }}-imagepull
    {{- end }}
    {{- if .Values.global.rbacEnable }}
      serviceAccountName: {{ include "alameda-ai.fullname" . }}
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
