apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app : alameter
  template:
      metadata:
        labels:
          app: alameter
      spec:
        #nodeSelector:
        #  kubernetes.io/hostname: "netmnyje67-worker-2"
        containers:
        - name: alameter
          image: containersai/alameter:latest
          imagePullPolicy: IfNotPresent
          ports:
          - name: gui-alameter
            containerPort: 8999
          #tty:  true
          # checking
          #livenessProbe:
          #  httpGet:
          #     path: /pda/
          #     port: 8999
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
          #  timeoutSeconds: 10
          #  successThreshold: 1
          #  failureThreshold: 3
          #readinessProbe:
          #  httpGet:
          #    path: /pda/api/
          #    port: 8999
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
          #  timeoutSeconds: 10
          #  successThreshold: 1
          #  failureThreshold: 3
          volumeMounts:
          #- mountPath: /var/lib/alameter
          #  name: alameter
          - name: localtime
            mountPath: "/etc/localtime"
            readOnly: true
          #- mountPath: /var/log
          #  subPath: alameter/alameter/alameter/varlog
          #  name: depot
          # mounted shared directory: /depot
          #- mountPath: /depot
          #  name: depot
          #resources:
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
          #  limits:
          #    cpu: 6.0
          #    memory: "2Gi"
        #initContainers:
        #- name: init-mgmt
        #  image: prophetservice/mgmt:running
        #  imagePullPolicy: Never
        #  command: ["sh", "-c", "/opt/prophetstor/federatorai/bin/init-pda.sh"]
        #  volumeMounts:
        #  - name: federatorai
        #    mountPath: /opt/prophetstor/federatorai
        #restartPolicy: Always
        # mount rook shared file system
        volumes:
        #- name: depot
        #  flexVolume:
        #    driver: rook.io/rook
        #    fsType: ceph
        #    options:
        #      fsName: rook-filesystem
        #      clusterName: rook-ceph
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        #- name: alameter
        #  hostPath:
        #    path: /home/core/alameter

