{{- if .Values.image.accessToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datahub.fullname" . }}-imagepull
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.datahub.name }}
data:
  .dockerconfigjson: {{ .Values.image.accessToken }}
type: kubernetes.io/dockerconfigjson
{{- end }}
