apiVersion: v1
kind: Service
metadata:
  name: {{ include "datahub.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.datahub.name }}
spec:
  type: {{ .Values.global.component.datahub.service.type }}
  ports:
    - port: {{ .Values.global.component.datahub.service.port }}
      protocol: TCP
      name: {{ .Values.global.component.datahub.service.name }}
  selector:
    app: alameda
    component: {{ .Values.global.component.datahub.name }}
