{{- if .Values.global.rbacEnable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datahub.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.datahub.name }}
{{- end }}
